openapi: 3.0.3
info:
  title: Quote API - OpenAPI 3.0
  description: |
    API for managing quotes
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /quotes:
    get:
      tags:
        - quote
      summary: Get all quotes
      description: Retrieve all quotes
      operationId: getAllQuotes
      parameters:
        - name: page
          in: query
          description: Page number default 1
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          description: Number of items per page default 10
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedGetAllQuotesResponse'
        '400':
          description: Invalid request

    post:
      tags:
        - quote
      summary: Add a new quote
      description: Add a new quote
      operationId: addQuote
      requestBody:
        description: Create a new quote
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quote'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Invalid request

  /quotes/{id}:
    get:
      tags:
        - quote
      summary: Get a quote by ID
      description: Retrieve a quote by ID
      operationId: getQuoteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: '5eb17aaeb69dc744b4e72a4a'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
        '404':
          description: Not Found
        '400':
          description: Invalid request
          
  /quotes/author/{author}:
    get:
      tags:
        - quote
      summary: Get quotes by author
      description: Retrieve quotes by a specific author
      operationId: getQuotesByAuthor
      parameters:
        - name: author
          in: path
          required: true
          schema:
            type: string
          example: 'Bill Gates'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quote'
        '404':
          description: Not Found
        '400':
          description: Invalid request

components:
  schemas:
    Quote:
      type: object
      properties:
        _id:
          type: string
          example: '5eb17aaeb69dc744b4e72a4a'
        quoteText:
          type: string
          example: 'The first rule of any technology...'
        quoteAuthor:
          type: string
          example: 'Bill Gates'
        quoteGenre:
          type: string
          example: 'business'
        __v:
          type: integer
          example: 0
    PagedGetAllQuotesResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Quote'
        pageable:
          type: object
          properties:
            sort:
              type: object
            offset:
              type: integer
            pageNumber:
              type: integer
            pageSize:
              type: integer
            paged:
              type: boolean
            unpaged:
              type: boolean
        totalElements:
          type: integer
        totalPages:
          type: integer
